### ISSUE TITLE
encode.py calculates the wrong time

### ISSUE THREAD

**Issue by maddin77** [AniDevTwitter/animeopenings#149]
The `HMStoS` function does `s * 60 + m` instead of `m * 60 + s`. Same goes for the `hh:mm:ss` conversion.

Also there's another error that i can't figure out since i can't python.

```
> ./encode.py -i orig.mkv -o opening.webm -e 01:30

Openings.moe 4.2 comfy encoder!

Input file: "orig.mkv"
Output file: "opening.webm"

Checking volume levels ...
Traceback (most recent call last):
  File "encode.py", line 167, in <module>
    volume = str(calcVolumeAdjustment())
  File "encode.py", line 86, in calcVolumeAdjustment
    subprocess.call(args, stdin=None, stdout=f, stderr=f)
  File "/usr/lib/python3.5/subprocess.py", line 560, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.5/subprocess.py", line 950, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1483, in _execute_child
    restore_signals, start_new_session, preexec_fn)
TypeError: Can't convert 'float' object to str implicitly
```
Only happens if you use `-s` and/or `-t`.

**Comment by Yay295** [comment]
oops, my bad. I'll put a fix up soon.

I'm not seeing your second issue though. I know what it's saying, but I don't know why it's saying it for you.

**Comment by QuadPiece** [comment]
@Yay295 can confirm that the float -> str error happens to me sometimes too. I tried looking through the file but couldn't find any issues myself. It appears to me that it only happens when I use `-e` without an `-s`

**Comment by maddin77** [comment]
@Yay295 If i do the same as 0a81c9e for `startTime` & `endTime-startTime` in `calcVolumeAdjustment` it seems like it's working correctly on my end now.

**Comment by QuadPiece** [comment]
Fix is now merged. Can someone else also confirm that this issue is no longer present in `encode.py` - It seems to be working on my end
