### ISSUE TITLE
Search doesn't work

### ISSUE THREAD

**Issue by halfnhalf** [AniDevTwitter/animeopenings#168]
`Uncaught TypeError: list[Symbol.iterator] is not a function list.js:9`
`Uncaught TypeError: list[Symbol.iterator] is not a function list.js:96`

the offending line

`for (var series of list) series.id = series.childNodes[0].nodeValue;`

**Comment by Yay295** [comment]
It still works in Firefox. I'm looking into a fix for Chrome (that will hopefully work in Firefox as well).

**Comment by Yay295** [comment]
This is definitely a bug in Chrome. I really hate having to fix their mistakes all the time...

**Comment by thehowl** [comment]
`$.each(array, function(key, value){});`?

On 17 March 2016 07:17:42 CET, Yay295 <notifications@github.com> wrote:
>This is definitely a bug in Chrome. I really hate having to fix their
>mistakes all the time...
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AniDevTwitter/animeopenings/issues/168#issuecomment-197725624

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thehowl** [comment]
or the ol' good

for (var i = 0; i < list.length; i++) {}

On 17 March 2016 07:17:42 CET, Yay295 <notifications@github.com> wrote:
>This is definitely a bug in Chrome. I really hate having to fix their
>mistakes all the time...
>
>---
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AniDevTwitter/animeopenings/issues/168#issuecomment-197725624

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Yay295** [comment]
Fortunately we seem to have avoided this problem in all 1500+ lines of subtitle code, so no other pages are broken.

**Comment by QuadPiece** [comment]
Changes pulled and confirmed working in Chrome - This is why I hate Chrome so much, it's like they don't know what standards are, then they just try pushing their own without warning.
