### ISSUE TITLE
eggs.php & undefined refresh/randomize button

### ISSUE THREAD

**Issue by Venrir** [AniDevTwitter/animeopenings#186]
Fix:
index.php {
remove the include_once "eggs.php";
add $eggs = [];
change $videos=$names + $eggs; to $videos=$names.$eggs;
}
api/list.php {
remove the include_once "../eggs.php";
add $eggs = [];
}

**Comment by Yay295** [comment]
Um, no.
1. `eggs.php` does exist on the server. It contains an array called `$eggs`.
2. The `.` operator is not defined for arrays.

**Comment by QuadPiece** [comment]
Frankly, maybe we should just add some checks to see if `eggs.php` exists before we include it. Having easter eggs (or needing to edit the code to get rid of them) shouldn't really be a thing.

Also it'd prevent issues like this in the future

**Comment by Yay295** [comment]
Sure, that'd be pretty simple to add.

**Comment by QuadPiece** [comment]
Closed by PR #188
