### ISSUE TITLE
?video=*name* gives 404 Error

### ISSUE THREAD

**Issue by Venrir** [AniDevTwitter/animeopenings#187]
![image](https://cloud.githubusercontent.com/assets/17952364/16363516/018a21bc-3bcd-11e6-982b-2160e0233443.png)

**Comment by Yay295** [comment]
Well, does `*name*` exist on the site?

**Comment by Venrir** [comment]
it has been solved, it was again these eggs[]

**Comment by QuadPiece** [comment]
Just realized that I forgot to close this
