### ISSUE TITLE
Use hashbang for "current video"

### ISSUE THREAD

**Issue by FichteFoll** [AniDevTwitter/animeopenings#213]
Instead of using GET parameters (`?video=`) hashbangs (`#!video=`) could be used. Ideally while also modifying the browsing history so that the browser's back button would work.

This allows to:

1. quickly sharing the current video (it's already in the locationbar)
2. resume watching the same video when closing the browser and opening it again on the same page (seems to be saved in a cookie currently?)
3. use the back button to watch the previous video (seems to work already although I don't see why)

**Comment by Yay295** [comment]
1. There's a link in the menu to the current video.
2. We don't use Cookies. This is saved because we use the [History API](https://developer.mozilla.org/en-US/docs/Web/API/History).
3. Also the History API.

http://stackoverflow.com/a/3009501/3878168

**Comment by FichteFoll** [comment]
Thanks for the links, they helped a lot.

1. I realize this is a possibility. I specifically meant to use the locationbar as a quicker tool.
2. Interesting, I didn't know you could push "state objects" along with a tilte to the history. That certainly explains things, although it is kinda intransparent.

So, considering what I learned from the links you posted (hashbangs were a hack that isn't needed anymore because we can push states and change the locationbar without reloading), I'll rephrase the feature request (or suggestion) to the following:

Reflect the currently shown video in the url for a more visible state change and easier sharing of the currently shown content.
Many sites do this already, like twitter or discourse installations.

**Comment by QuadPiece** [comment]
We actually used to keep the filenames in the URL field for sharing before, I have no idea who removed this, when they did it and why.

imo we should bring direct links in the URL bar back like he suggested. I hadn't even noticed they were gone until now.

**Comment by Yay295** [comment]
I remembered why we removed the video from the url - if the video is in the url, refreshing the page will always give you the same video instead of getting a new one. Though that doesn't work anyways because the video is set in the history state, so showing it in the url doesn't change anything.

**Comment by QuadPiece** [comment]
Ah, that sounds fair. Regardless this issue is closed now since direct links stick now. Refreshing should be intended behavior. We have a button and hotkey (N) to get new videos for a reason.
