### ISSUE TITLE
Moving away from jQuery?

### ISSUE THREAD

**Issue by Sylphony** [AniDevTwitter/animeopenings#266]
Out of curiosity, is the JS code in the progress of being converted from jQuery to vanilla?

I can't help but notice that both are being used and in a number of areas, it seems to me it would be better (in terms of consistency and cleanliness) that jQuery is used.  If it is in the progress of being converted into vanilla (ES6 I assume) then that would make sense to me.

**Comment by Yay295** [comment]
jQuery has been removed in #279
