### ISSUE TITLE
Effect don't work properly

### ISSUE THREAD

**Issue by Rinchama** [AniDevTwitter/animeopenings#270]
Hi,

When a line contains: {\K90}{\K42}yami {\K20}no {\K42}hou {\K27}ga {\k48}SU{\k46}TE{\k38}KI
It work,

When a line contains: {\k56}{\K41}hai{\K35}yori{\K31}masu{\K17}ka {\K48}sei {\K17}no {\K21}u{\K18}ne{\K34}ri
It does not work.

So using \K followed by \k works but not conversely.

for example : http://betav2.karaokes.moe/?video=Haiyore!Nyaruko-sanW-Opening and http://betav2.karaokes.moe/?video=Haiyore!Nyaruko-san-Opening

**Comment by Rinchama** [comment]
With the modification I tested, the display is shifted (and appears too early)

And it does not work properly with this video for example: http://betav2.karaokes.moe/?video=Eggs-Ah!MyGoddess-AMV-ShiningCollection

**Comment by Yay295** [comment]
b6e852120d5c4f7473879bd5320acf6b8b8af626 will fix some of that

**Comment by Rinchama** [comment]
It is no longer shifted with this last modification but ...

It does not work properly in this case:

Dialogue: 0,0:00:45.98,0:00:51.95,kara,,0,0,0,,{\k90}{\k31}KISS {\K70}SHI{\K78}NING {\k31}hi{\k39}to{\k35}mi {\k35}ni {\k29}ku{\k39}chi{\k38}zu{\k37}ke{\k35}te
Dialogue: 0,0:00:51.28,0:00:57.58,kara,,0,0,30,,{\k90}{\k34}to{\k38}ke {\K68}da{\K57}su {\k14}ha{\k39}na{\k26}bi{\k44}ra {\k23}mo {\k47}ja{\k31}ma {\k36}ni {\k40}na{\k33}ru

http://betav2.karaokes.moe/?video=Eggs-Ah!MyGoddess-AMV-ShiningCollection

**Comment by Yay295** [comment]
https://github.com/AniDevTwitter/animeopenings/pull/271/commits/a5b64e80b06ef385a4e950e65294171614bdad3d fixes everything

**Comment by Rinchama** [comment]
Works fine now
Thanks
