### ISSUE TITLE
Video not loading

### ISSUE THREAD

**Issue by WillyReyno** [AniDevTwitter/animeopenings#283]
Hi everyone, 

I tried to clone the project, but I get some error when loading the page.

Here is what I get in my Chrome console (same thing happens in firefox) : 
```
main.js:25 Uncaught TypeError: Cannot read property 'src' of undefined
    at filename (main.js:25)
    at window.onload (main.js:75)
```

I tried to look into the code and it seems that videos are looped with `foreach ($video['mime'] as $mime)` in index.php, but the `$video` doesn't seem to have mime in it. 

Thank you

**Comment by Yay295** [comment]
That would be because I forgot to update `names.php.sample`. #284

**Comment by WillyReyno** [comment]
Thank you! Do you use something to generate your names.php ?

**Comment by Yay295** [comment]
We have a few Python and Bash scripts, that aren't on GitHub, that handle everything from encoding the videos to deploying everything.
