### ISSUE TITLE
Android native application

### ISSUE THREAD

**Issue by yvlad** [AniDevTwitter/animeopenings#288]
Is anyone making native version of this project for android?
If no one, I will start. Or just join to existing development, if there is any.

Also, please, update API documentation. Mention, that developers can get link to video stream by adding `http://openings.moe/video/` to it's filename.

![screenshot_1508091012](https://user-images.githubusercontent.com/27954603/31587639-e02f33f2-b1ed-11e7-8db1-ffd71a1e100b.png)

**Comment by Yay295** [comment]
I think someone was going to make one a year or two ago, but I don't know what happened with that.

I've updated the API documentation [here](https://openings.moe/Yay295/test/hub/dev/api.php), but the main site hasn't been updated to use the latest code yet. `https://openings.moe/Yay295/test/` is current, but it only has the video files for two endings: Gosick ending 1 and Koyomimonogatari ending 1.

**Comment by yvlad** [comment]
OK, thx for response.

Please, delete this issue, I hadn't noticed, that it is my work account :(
