### ISSUE TITLE
[Quastion ] How to use ass subtitle.js with videojs player

### ISSUE THREAD

**Issue by sandyAI** [AniDevTwitter/animeopenings#290]
hello
how to use subtitle.js ass with videojs 
that would be good if there an example ?

thanks

**Comment by Yay295** [comment]
I haven't fully tested it, but this should work.
```
let VideoElement = document.getElementById("id_of_the_video_element");

VideoElement.style.margin = "auto";
VideoElement.style.position = "static";
VideoElement.parentElement.style.display = "flex";

SubtitleManager.add(VideoElement);
SubtitleManager.setSubtitleFile(VideoElement, "/subtitle/file/url.ass");
SubtitleManager.show(VideoElement);
// or
SubtitleManager.add(VideoElement, "/subtitle/file/url.ass", true);
```

The rest of the `SubtitleManager` methods are listed at the top of the `subtitles.js` file.

**Comment by sandyAI** [comment]
dosen't work ,,
any example ? i used videojs

**Comment by Yay295** [comment]
I got it working here https://openings.moe/Yay295/videojs_test.html

**Comment by sandyAI** [comment]
thanks, now its fine ,,
i notice there a problem in \N
the top text is getout of container and display the bottom text only !
ex: Before it gets too heavy and falls\N(Let's fly high)
only "(Let's fly high)" display and "Before it gets too heavy and falls" didn't

**Comment by Yay295** [comment]
Do you have an example online somewhere I can see of \N not working?

**Comment by TimotheAlbouy** [comment]
If I want to use your ASS renderer, do I just have to download the `subtitles.js` file or are there any dependencies to this file?

**Comment by Yay295** [comment]
There are no dependencies. If you want to see how we use it, it's at the bottom of `main.js`.
