### ISSUE TITLE
Broken og:video:type content

### ISSUE THREAD

**Issue by altbdoor** [AniDevTwitter/animeopenings#294]
In reference to the [code line below](https://github.com/AniDevTwitter/animeopenings/blob/master/index.php#L102):

```php
echo "\n\t\t" . '<meta property="og:video:type" content="' . $mime . '">';
```

When visiting the opening for [Hidamari Sketch](https://openings.moe/?video=Opening1k-HidamariSketch%C3%97365), the nested content value corrupts the HTML tag.

```html
<meta property="og:video:type" content="video/webm;codecs="vp9,opus"">
```

**Comment by Yay295** [comment]
Fixed. Thanks for pointing it out.
