### ISSUE TITLE
Long names are unreachable

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#298]
We have some fairly long video names in our database due to our own format. Is there a way to fix this?

Example : 

http://live.karaokes.moe/?video=%20Opening%20-JAP%20-%20Uta%20no%20Prince-sama%20Sweet%20Senerade%20

If you click on the first series it suggests and then opening 1, it fails and 404s.

**Comment by Yay295** [comment]
It's definitely not too long. I think it's because of the space at the end, which is probably something I can work around. I'll look into it.

**Comment by Yay295** [comment]
I think I figured it out, and it's not the space at the end. In our data the video index is padded, so "Opening1-Series" becomes "Series-OP**0**1-". This is done in `backend/includes/helpers.php`. Just change the last line in the `identifierToPartialFilename` function to `return $name . '-' . $oped  . $index . '-';`.

**Comment by AxelTerizaki** [comment]
Hmmm, I modified the file as you said, but links stilld o not work properly.

Check the videolist at http://live.karaokes.moe to see for yourself.

**Comment by AxelTerizaki** [comment]
I've tried a few things, notably deleting spaces from the "type" field but it doesn't fix the issue yet.

Here's our names.php for reference : 

http://live.karaokes.moe/names.php.txt

**Comment by Yay295** [comment]
https://github.com/AniDevTwitter/animeopenings/commit/b346b7e1849e4072d95670b1b979fc4caa169665 should have fixed it. You'll still need to modify that line I mentioned before though.

**Comment by AxelTerizaki** [comment]
That rocks, it works!

Is there a way to make that modification permanent though, I'd hateo to have to redo that fix whenever you modify the helpers file.

**Comment by Yay295** [comment]
I've added a config file. Just change the padding to 0 for your case.

**Comment by AxelTerizaki** [comment]
Yay for config file! This closes the issue for me then, thank you
