### ISSUE TITLE
Handle 0*0 PlayResX/PlayResY in ass files

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#300]
Hello :)

In our video database, we have various resolutions... well, a lot of them actually. On all of our mp4/h264 videos there are about 40 different heights.

As a result, most of our ass files for karaoke do not have a PlayResX/PlayResY metadata, mainly because we're still in the process of replacing low-quality videos by h264, HD versions whenever we can (on about 5800 videos, this takes some time)

We use mpv to display karaoke videos in our app (http://mugen.karaokes.moe/en) and it works just fine with PlayResX/PlayResY at 0. However, on AnimeOpenings, such ASS files make the subs appear really small.

Would there be a way to either handle 0*0 resolutions so text appears bigger? Or have it as something configurable, even, please?

That'd really be neat :)

**Comment by Yay295** [comment]
This should fix it. https://github.com/AniDevTwitter/animeopenings/commit/6b25d74b590d8818977f4cac88a4d149e0c25128

We were already handling missing and 0 values, just not correctly.

**Comment by AxelTerizaki** [comment]
I confirm it fixes the issue \o/
