### ISSUE TITLE
Subs for videos in 4:3 format aren't aligned properly

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#301]
It might be a side-effect of the fixes applied for #300, but when watching a 4:3 video, subs aren't quite aligned properly : 

![firefox_2018-07-30_08-13-21](https://user-images.githubusercontent.com/4531597/43380348-2131d9fc-93d1-11e8-8235-8b8655b730e6.png)

Note that I use Stylus to replace CSS on sites since I'm visually impaired (light blinds me a lot). When I enable it, it feels like the subtitle layer is off compared to the video : 

![firefox_2018-07-30_08-19-31](https://user-images.githubusercontent.com/4531597/43380392-510905f6-93d1-11e8-850a-87b126a0d07a.png)

Here's the ASS file in question : 

https://lab.shelter.moe/karaokemugen/karaokebase/blob/master/lyrics/FR%20-%20Freakazoid%20-%20OP.ass

And the video : 

https://www.dropbox.com/s/7hzoy2g2zw7qp3s/FR%20-%20Freakazoid%20-%20OP.mp4?dl=0

Sorry for creating so many issues, we have a lot of edge cases ^^

**Comment by Yay295** [comment]
Fixed with https://github.com/AniDevTwitter/animeopenings/commit/cc552a129ba9d869ac73ab75736ff6b8bcad57ff
I forgot to add "px" again.

**Comment by AxelTerizaki** [comment]
I confirm it fixes things, thank you so much !
