### ISSUE TITLE
\kf doesn't work in Firefox

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#302]
Even though \kf seems to work fine according to the docs, I found a use case when it does not : 

http://live.karaokes.moe/?video=%20Opening%20-FR%20-%20Il%20etait%20une%20fois%20la%20Vie%20

On this particular video we have sometimes \k or \kf and not all the letters are getting colored (on Firefox at least)

Here's the ASS : 

https://lab.shelter.moe/karaokemugen/karaokebase/blob/master/lyrics/FR%20-%20Il%20etait%20une%20fois%20la%20Vie%20-%20OP%20-%20Hymne%20a%20la%20Vie.ass

**Comment by Yay295** [comment]
It's not because they're being used together; \kf doesn't display properly in Firefox. See https://openings.moe/?video=Ending1-Gosick as well. It does work in Chrome though. I know I've had this problem before, so I'll have to look into it again.

**Comment by Yay295** [comment]
It should be fixed now.

**Comment by AxelTerizaki** [comment]
I confirm it works, thank you so much. I'll close the issue :)

**Comment by AxelTerizaki** [comment]
Apparently your fix broke something with Chrome : \kf isn't smooth at all there for some reason... Should I open another issue?

**Comment by AxelTerizaki** [comment]
(you can check out the link in the first post, try it out with chrome if you can, no problems with Safari

**Comment by Yay295** [comment]
I'm not seeing any problems in Chrome. Does it look like it's stuttering, or skipping ahead?
