### ISSUE TITLE
Long subs on a 4:3 video display out of bounds

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#304]
Making AnimeOpening better, one issue at a time :)

Here's the Love Hina opening (in french, yes.)

https://live.karaokes.moe/?video=0ababbb9-e0dd-4c8c-bf46-315eadfe9dfd

As you can see once the lyrics appear, they're too long for the width of the displayed video.

I suppose you could either implement some sort of word wrap or perhaps draw subs outside of the video? Not sure if this would work well, all things considered...

**Comment by AxelTerizaki** [comment]
I realize I didn't update the issue with our latest developements, causing the former link to 404. I'm going to edit the initial post to change the URL to one with the issue mentionned.

**Comment by Yay295** [comment]
847b3f33429f8e0adecf17f28349a3bc1e28d06d should solve most of your issues here. The bugs it still has are that it accidentally kills paths that are in a long line, and it doesn't re-break the line on transitions for some reason.

**Comment by AxelTerizaki** [comment]
Thank you so much! We merged AO on Live.karaokes.moe and indeed, it wraps lines now!

I'll reopen the issue if we run into this again, but for now at first glance it seems to run just fine.

**Comment by AxelTerizaki** [comment]
Reopening now :)

Apparently it cuts lines in the middle of words, example here :

https://live.karaokes.moe/?video=1266932b-3115-4651-9c38-2ad93e2d376d

the word "being" is cut in "be" and "ing".

I suppose this is due to the karaoke ASS tags making it seem like these are two words. 

Would it be possible to wrap lines at spaces instead of in the middle of words?

Thanks :)

**Comment by Yay295** [comment]
Oh, that's a good point.

**Comment by Yay295** [comment]
I think 21da272 should have fixed that.

**Comment by AxelTerizaki** [comment]
Sorry for not replying earlier, it works fine now, thank you :)
