### ISSUE TITLE
Spacing between lines too big on Chrome

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#308]
Hello again :)

This is a very minor issue, but since #297 was fixed (thank you again) Chrome seems to put too much spacing between lines.

Here's a screencap from firefox : 

![firefox_2018-08-29_17-52-12](https://user-images.githubusercontent.com/4531597/44799727-eccb2780-abb4-11e8-9af6-8676e8d6c0af.png)

And about the same one from chrome : 
![chrome_2018-08-29_17-50-30](https://user-images.githubusercontent.com/4531597/44799763-040a1500-abb5-11e8-825e-ba8921725311.png)

(don't mind the color change, it's from me using Stylus on FF) 

That'd be nice if it could be fixed sometime, thanks :)

**Comment by Yay295** [comment]
I don't know when I'll get to this, but I noticed it on https://openings.moe/?video=Insert1a-ShoujoKakumeiUtena too. Just leaving a note for my future self.
