### ISSUE TITLE
\kf ASS tags are filled after being "sung" instead of during

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#309]
This isn't a big problem but still worth mentionning.

When \kf is used (not \k) the syllabe is filled after it's been sung, instead of during, shifting the whole karaoke as a result.

\k is more commonly used because of how romanji is separated pretty easily, but when we have songs in other languages, it feels more natural to use \kf.

I'll post an example as soon as I can get one from the person who told me about this issue

**Comment by Yay295** [comment]
Do you have an example with slower subs? It might be that the subs are lagging behind, so they're just jumping to the end instead of slowly filling up. I wouldn't think those subs are complicated enough for that to happen though...

**Comment by Rinchama** [comment]
Off course, this is OK ?
https://live.karaokes.moe/?video=%20Opening1%20-FR%20-%20Jushi%20Sentai%20France%20Five%20

**Comment by Yay295** [comment]
I'm not seeing any issues. The only thing I can think of is that on a slow computer it might be possible for the subtitles to be lagging behind the audio. These subtitles really aren't that complicated though, so it would have to be a very slow computer.

**Comment by AxelTerizaki** [comment]
I believe you're right, the computer this was tried on is quite old and might be a bit slow. A workaround for this would be to use \k instead of \kf.

Nothing you can do there, I'll close the issue then ^^
