### ISSUE TITLE
When two words have different colors on the same line, some syllabes aren't colored the right way

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#310]
It's not a big issue either and a little hard to explain but I try.

Image 1 : 
https://gyazo.com/d5ec0aca127d348b1837b39de3ab864d

Image 2 : 
https://gyazo.com/1c2cbf8ba13a7e9bb3e4d953a2a32b1e

Image 1 is taken from AnimeOpenings, image 2 with mpv.

This karaoke can't be linked due to a bug (when there are two or more songs with the same name, no matter what you link, it's always the first one that's displayed, we'll create an issue later for that) but this one displays the same behavior : 

https://live.karaokes.moe/?video=%20Opening%20-ANG%20-%20ACCA%2013-ku%20Kansatsuka%20

When a word is of a different color, than the rest of the line, its first syllabe stays in the original line's color.

On ACCA the behavior is even weirder, see : https://gyazo.com/8b309983027cb5ce56a3f863bf4d88d4 the word "story" is suppoed to be in yellow.

You can find video and ASS files for ACCA here : 
http://mugen.karaokes.moe/en/karas/6696c027-7bb2-4bc5-a973-0e034569d50c.html

The first karaoke I showed was Tutu Ballerina which you can find files for here : 
http://mugen.karaokes.moe/fr/karas/e58ff527-7f84-4f86-a4ba-7381f7efd2ff.html

Hope this can help :)

**Comment by AxelTerizaki** [comment]
We've just found a workaround for this : the problem occurs when you have text in some color (say blue) then a \kf or \k tag, then another color (say red). In this configuration, AnimeOpenings displays the word after the \k tag as blue instead of red.

However, if you put the color tag BEFORE the \kf or \k tag, the color is rendered correctly.

The ACCA ass file has been fixed when we wanted to test things out on this issue and it worked. Note that on mpv, this problem isn't occuring (hence why it surprised us on AnimeOpenings)

**Comment by AxelTerizaki** [comment]
As an example : 

If you have `<color1>{\k}bla{\k}bla{\k}bla  {\k}<color 2>lo{\k}lo{\k}lo,` the first lo stays with color1 while the rest is correctly colored.

In order for colors to render correctly, you have to write `<color1>{\k}bla{\k}bla{\k}bla <color2>{\k}lo{\k}lo{\k}lo

**Comment by AxelTerizaki** [comment]
Also, (sorry for the spam) the problem occurs if the color tag (\c or \2c) is inside the same {} as \k

**Comment by AxelTerizaki** [comment]
When two different color tags are present (like \c and \2c) together to redefine a text's color, only one of them gets applied.
We wanted to use the reset tag (\r) but AO doesn't seem to have it.

You can see at around 1min10 on this particular karaoke what the issue is :
https://live.karaokes.moe/?video=JAP%20-%20Momo%20Kyun%20Sword%20-%20ED%20-%20Momo%20Kyun%20Sword

**Comment by Yay295** [comment]
I think 3c97df8 might fix this.

**Comment by AxelTerizaki** [comment]
Thanks you! I'm going to test it out before next week and will keep you updated.

**Comment by AxelTerizaki** [comment]
Okay, I confirm it works : 

https://live.karaokes.moe/?video=e58ff527-7f84-4f86-a4ba-7381f7efd2ff

I'm closing the issue, thanks again for your work :)
