### ISSUE TITLE
[request] search button in the top right corner

### ISSUE THREAD

**Issue by ivesen** [AniDevTwitter/animeopenings#313]
I'd like for a search button in the top right that opens the video list
this way I can save a full click! And that's vitally important you know

**Comment by Yay295** [comment]
I'm not saying it's never going to be added, but it's probably never going to be added.

**Comment by AlgusDark** [comment]
Maybe this can be added on the API and then that's going to be easier to create the JS part.

**Comment by Yay295** [comment]
Getting the list is already part of the API. https://openings.moe/hub/dev/api.php

**Comment by AlgusDark** [comment]
I was thinking on having a new API for search, like:

`list.php?q=XXXXXX`, if not, we need to search an entire array with JS (maybe with filter).

**Comment by QuadPiece** [comment]
To be fair, the video list is a fairly vital component for browsing the site. And having an easily accessible search button is probably better UX than it being a bullet point in a list (that's not even visible by default)

We already have the code, ivesen just wants us to move the "Video List" link from being a menu item, to being an "fa-search" icon.

**Comment by Yay295** [comment]
added 055095358659280ab75b47982d09d998d2b1e827
