### ISSUE TITLE
Subtitles vertical margin is applied to all lines instead of only the first one

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#315]
Hello :)

This has been tested with a version pulled from this repo on Apr 28th 2019.

This is visible on this karaoke : 
https://live.karaokes.moe/?video=69d2440d-7dcb-42e4-aad1-2361136a6ed3

In the ASS style, vertical margin is defined at 75.

![Aegisub](https://lab.shelter.moe/karaokemugen/sites/live/uploads/a0deb4bc6c055b1bb6df2ef2317fc4e2/aegisub.png)

Here's how it's displayed in AnimeOpenings :

![AO](https://lab.shelter.moe/karaokemugen/sites/live/uploads/5fd42ae00ae038b04f4471fbae814041/AO.jpg)

Here's how it's displayed in mpv :

![mpv](https://lab.shelter.moe/karaokemugen/sites/live/uploads/4ad6af25096494f278a3a6c9e2e9fed8/mpv.jpg) 

As you can see, the vertical margin is only applied to the first line in mpv, whereas in AO it's applied to all lines, making the subs quite spaced out on screen when you have multiple lines.

Could this possibly be fixed sometime? 

Thanks in advance :)

**Comment by Yay295** [comment]
Actually, the second line has a vertical margin of 120.

    Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
    Dialogue: 0,0:00:17.02,0:00:19.40,en haut,,0,0,120,fx,{\k90\fad(300,200)}{\k11}Ba{\k10}ka-{\k14}mhm {\k15}bak-{\k19}mhm {\k13}bak-{\k22}bak-{\k24}bak

Which is still not enough because that would cause them to overlap, so I think the problem might be in the collision handling code somewhere. I've only just glanced at this so far though.

**Comment by Yay295** [comment]
try 02674d5

**Comment by AxelTerizaki** [comment]
I confirm this fixes the issue. Thanks for the quick fix! :)
