### ISSUE TITLE
Some peculiar ASS problems

### ISSUE THREAD

**Issue by AxelTerizaki** [AniDevTwitter/animeopenings#321]
Hello :)

We recently added a new karaoke on our fork of AnimeOpenings at http://live.karaokes.moe

https://live.karaokes.moe/?video=1e445b6a-e919-4d80-8cec-00422a405ecc

As you can see, this is some heavy weight ASS fun, and I honestly doubt you can do anything about it on your end to display it better but I'm creating an issue anyway just in case you want to look into it. 

The "die" word in particular should disappear and appear way better. I invite you to check out the video + ass (which are downloadable from the menu) and see for yourself in vlc/mpv/mpc

**Comment by AxelTerizaki** [comment]
Sorry for the late response.

I applied your commit but it doesn't seem to change a thing (you can check via the same link in the issue)

**Comment by Yay295** [comment]
It removed the exceptions that were showing up in the console at least.

**Comment by Yay295** [comment]
Alright, I've pushed another fix. 11637f3095cb4a55a3b2dae180f526be850eb0bc

**Comment by AxelTerizaki** [comment]
Works perfectly!

Thank you, I'll close that now :)
