### ISSUE TITLE
Playing only Insert Songs is broken

### ISSUE THREAD

**Issue by ninjamask** [AniDevTwitter/animeopenings#327]
Steps to reproduce:
1. Set the **Show Video Types** in the **Saved Settings** menu to only allow **Inserts**
2. Play Songs

**Comment by Yay295** [comment]
Getting the same video over and over?

**Comment by ninjamask** [comment]
yes

**Comment by Yay295** [comment]
It's been a while, so I thought I should at least say something. I know what the issue is, but I don't have a solution yet. I'm still working on it.
